lib/neo_kitten_web/router.ex
defmodule NeoKittenWeb.Router do
  use NeoKittenWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NeoKittenWeb do
    pipe_through :browser

    get "/", VoteController, :index
    post "/vote/w/:winner/l/:loser", VoteController, :vote

    get "/stats/", StatsController, :index

    get "/cutest", RankingController, :cutest
    get "/latest", RankingController, :latest

    get "/reset", ResetController, :index
    post "/reset", ResetController, :reset
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoKittenWeb do
  #   pipe_through :api
  # end
end

lib/neo_kitten_web/views/layout_view.ex
defmodule NeoKittenWeb.LayoutView do
  use NeoKittenWeb, :view

  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end
end

lib/neo_kitten_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>NeoKitten</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Vote", to: Routes.vote_path(@conn, :index)%></li>
            <li><%= link "Stats", to: Routes.stats_path(@conn, :index)%></li>
            <li><%= link "Cutest", to: Routes.ranking_path(@conn, :cutest)%></li>
            <li><%= link "Latest", to: Routes.ranking_path(@conn, :latest)%></li>
            <li><%= link "Reset", to: Routes.reset_path(@conn, :index), class: "reset"%></li>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>